### ISSUE TITLE
Binary data file as input

### ISSUE THREAD

**Issue by kimjohn1** [blackears/godot_volume_layers#3]
Love this Godot add-on.
I'm working on a project to render visuals from data produced by physics simulation.  The data of interest right now is scalar field data, output as a binary file.  The files produced by the type of simulation I am running can be quite large, but I am using GPU accelerated laptop and PC computers rather than supercomputers, so I tailor the simulation accordingly, and the output files are up to around 500 MB in size.  Your ReadMe text describes creating a packed file of .png images for input.  Is that the only option for input?  The Online Converter website that you mention limits the input file to less than 200 MB, so I may be out of luck there.  Are there other converter applications, or could I format the output myself to make if readable by your add-on?
Keep up the good work!
Thanks,
Kim

**Comment by blackears** [comment]
I used the converter because it seemed to be the easiest way to convert MRI scan data into something Godot could process.  If you're a programmer, you could dump the vector data into your own file format and then write a custom loader for that format in the addon.  I've not touched it in a while, but if I recall correctly it can use any Texture3D as data, so if you write your own class which extends Texture3D, it should be able to use that.

**Comment by kimjohn1** [comment]
Thank you for responding.  This is just what I need to know.
I'm not a programmer myself, but I have had assistance from a number of very skilled programmers from time to time during the course of this project.
You suggest that I might save my simulation output in a custom file format and then modify Godot to be able to input that file format.  Well, could I just save the output in a file format that is already able to be input to Godot?  If so, can you recommend a format that would be appropriate for me to use?  I see ImageTexture3D in the VolumeLayers texture dropdown menu.  Would that work?
Thanks again for your help here.  I believe we are almost done.
Kim

**Comment by kimjohn1** [comment]
Got 'er done.  My son wrote the code to convert raw output from my simulation into a set of .png files.  Your shader reads that just fine, and I now have it running in VR:

<img width="1139" alt="simple_wave_3_with settings" src="https://github.com/user-attachments/assets/01b6858e-5fcf-445b-afe7-5004b127af2b">

and a boring video of the image in VR:
(https://www.youtube.com/watch?v=Qrib7G82E34)

Closing the issue.  Thanks for the help, and thanks especially for the volume_layers add in.
Kim

**Comment by blackears** [comment]
Hi Kim,

Sorry for not getting back to you sooner.  I missed your Sep 14 reply.  

I'm glad your son was able to get this working for you.  Godot does have the ability to save ImageTexture3D, but it's very bulky and I'd recommend using a binary format you design yourself.

If you look at res://addons/volume_layered_shader/scripts/resources/cpu/zipped_image_archive_cpu_Texture3D.gd, you can see how I used an ImageTexture3D as a base and added a load_image_from_zip() method to load the data from a file.  I also added a parameter called zip_file to my custom 3D texture and created a custom setter for it so that setting it will automatically trigger the file to be reloaded.  Finally, I had to override the _validate_property() method so that the _images property is not saved in the resource file.  This is necessary to prevent all the image data from being duplicated in the save file - it's also not necessary since the data is being loaded from the save file.

Anyhow, it looks like you've already got a solution, but if you need something more accurate, you could create something like the zipped_image_archive_cpu_Texture3D but using your own custom file format.

Your particle image looks pretty impressive.  I don't know a lot of about quantum physics, but it look fascinating.

**Comment by blackears** [comment]
I'm not sure if you'd find this useful, but I also have another project that uses marching cubes to turn density fields into geometric meshes: https://youtu.be/6LETzlfixK8

**Comment by kimjohn1** [comment]
Thanks for the info regarding construction of a custom data input capability.  I will be able to put that to use in due time. For now, I am pressing on with implementing output of a .png dataset directly from the simulation, and using that to demonstrate the ability to show a visualization as the simulation is running.
I am indeed interested in the marching cubes visualization.  I have it running on my Linux machine and plan to have it working in VR on the Windows machine in the next couple of weeks as time allows.
![cubes_on_O2](https://github.com/user-attachments/assets/4ace6a82-4ecc-4b9b-b0ec-6623fb58989c)

and a short video, at (https://youtu.be/KUBadU9UaF4)

Thanks again for the capabilties!

**Comment by kimjohn1** [comment]
Just a note: retrieving both the Volume Shader and the Marching Cubes from the Releases page does not include the art.  The art folder is present but no Iguana or other .zip files.  In both cases I had to go back to the main repository page and download the repo as a zip file to get the art files.

**Comment by blackears** [comment]
The iguana model should be there.  It should be under /godot/art/iguana.  I don't want to check in more than that because the files are large and I don't own the copyright.

https://github.com/blackears/godot_volume_layers/tree/master/godot/art/iguana
